# Generated by Django 3.2 on 2023-06-08 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('is_complete', models.BooleanField(default=False)),
                ('dead_line', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.PositiveSmallIntegerField(choices=[(1, 'Work'), (2, 'School'), (3, 'Personal'), (4, 'urgent'), (5, 'travel'), (6, 'social'), (7, 'Family'), (8, 'deadlines'), (9, 'goals')], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
